### ISSUE TITLE
Exception of interactive rendering

### ISSUE THREAD

**Issue by mifth** [bsavery/PRMan-for-Blender#102] opened 2015-08-09 09:55 UTC
Hi.

I had Interactive rendering switched on.
Then I Closed 'it' and opened another blend file (Ctrl+O).

But interactive rendering was still switched on.
Then i tried to swtch interactive rendering off and got exception http://i.imgur.com/H49aCyO.png

**Comment by bsavery** [comment] 2015-08-09 12:28
Understood. Thanks

On Sunday, August 9, 2015, mifth <notifications@github.com> wrote:

> Hi.
>
> I had Interactive rendering switched on.
> Then I Closed 'it' and opened another blend file (Ctrl+O).
>
> But interactive rendering was still switched on.
> Then i tried to swtch interactive rendering off and got exception
> http://i.imgur.com/H49aCyO.png
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/102>.
>


-- 
brian.savery@gmail.com
508-274-8700

**Comment by bsavery** [comment] 2015-08-09 13:19
This is a duplicate of this issue:
https://github.com/bsavery/PRMan-for-Blender/issues/80

**Closed by bsavery** 2015-08-09 13:19 UTC
Labels: duplicate
