### ISSUE TITLE
TIFF output not working as expected

### ISSUE THREAD

**Issue by davemj** [bsavery/PRMan-for-Blender#131] opened 2015-09-08 01:22 UTC
Not sure if this is an issue or not, but when I select Tiff as the output, the files which come out are tagged with the IFF extension, is there any way of getting them to come out with TIF as an extension. The TIF files themselves are fine, but the extension is confusing After Effects and some other applications.

My current work around is to rename all the files, and then all is well (as far as I have tested it)

**Comment by MWY3510** [comment] 2015-09-08 01:52
I'll take a look at this.

**Comment by MWY3510** [comment] 2015-09-08 02:09
Ok, the issue is fixed and will be in my next merge request. It was simply an assumption in the user_path function.

**Closed by MWY3510** 2015-09-08 02:09 UTC
