### ISSUE TITLE
Force field physics setting missing on renderman

### ISSUE THREAD

**Issue by boboalice** [bsavery/PRMan-for-Blender#474] opened 2017-04-12 12:05 UTC
on the physics data tab the force field setting are missing when switching to renderman.

![miss](https://cloud.githubusercontent.com/assets/27031391/24956544/becb6eb4-1f90-11e7-8919-0d992d083ecc.jpg)

blend file:
http://s000.tinyupload.com/download.php?file_id=82815135272598812265&t=8281513527259881226553823

**Comment by bsavery** [comment] 2017-04-12 22:19
Going to close this as it's a duplicate of this one:

https://github.com/bsavery/PRMan-for-Blender/issues/474

**Closed by bsavery** 2017-04-12 22:19 UTC

**Comment by boboalice** [comment] 2017-04-13 06:58
i can't seem to find it, it's the same one !?
